trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages: 
 - stage: DevTest
   jobs:
   - job: Build
     steps:

      - task: DotNetCoreCLI@2
        inputs:
          command: 'restore'
          projects: '**/*.csproj'
        displayName: 'Restore Nuget Packages'
      
      - task: DotNetCoreCLI@2
        inputs:
          command: 'build'
          projects: '**/*.csproj'
          arguments: '--no-restore'
        displayName: 'Build projects'
      
      - task: DotNetCoreCLI@2
        inputs:
          command: 'test'
          projects: '**/*Test.csproj'
          arguments: '--no-restore --no-build'
        displayName: 'Run Tests'
      
      - task: DotNetCoreCLI@2
        inputs:
          command: 'publish'
          publishWebProjects: false
          projects: '**/*.csproj'
          arguments: '--configuration $(buildConfiguration) --no-restore'
          modifyOutputPath: false
        displayName: 'Publish WebApplication'


      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(Build.ArtifactStagingDirectory)'
          artifact: 'drop'
          publishLocation: 'pipeline'